Lading page hero
kvlsndkf/here pull request #2
Opened 2022-02-25 23:22 UTC by emillienicole

2022-02-27 14:50 UTC, MayaraPereira17 reviewed
tirar 1 body por que tem dois   não é necessário , e deveria comentar  o que é cada parte do codigos

2022-02-27 14:50 UTC, MayaraPereira17 commented on index.php
> +    </body>
tem 2 body

2022-02-27 14:50 UTC, MayaraPereira17 commented on index.php
> +    <body>
outro body

2022-02-27 19:02 UTC, hmiranda99 requested changes

2022-02-27 19:02 UTC, hmiranda99 commented on views/styles/index.style.css
> +}
Com o backgound da navbar em uma cor clara, não temos um contraste bonito com a página, visto que ela é em tons pastéis com detalhes em roxo escuro.

**Melhoria** : mudar a logo e as labels para branco e o background da navbar ser da cor das labels (roxo escuro).

2022-02-27 19:02 UTC, hmiranda99 commented on views/styles/index.style.css
> +
Já usamos um scroll na área da comunidade.

**Melhoria** : Seguir o mesmo estilo para que tenhamos uma padronização no projeto

![Captura de tela 2022-02-27 155455](https://user-images.githubusercontent.com/79329906/155895771-4298f250-564d-42f2-9b52-6546496795ad.png)
.

2022-02-27 19:02 UTC, hmiranda99 commented on index.php
> +            </div>
O corpo da lading page tem um container, ou seja, um mesmo espaço do começo ao fim. A navbar segue este espaço, porém o hero está quebrando esse espaçamento.

**Melhoria** : Diminuir um pouco o título, quebrar a linha do subtítulo, diminuir um pouco a imagem e usar a `class="container"` do bootstrap. Questões de layout serão mudadas no protótipo pela UX, para facilitar a vida do front.

2022-03-01 17:59 UTC, emillienicole commented on index.php
> +    </body>
> 

Obrigada pelo aviso! Vou retirar

2022-03-01 18:02 UTC, emillienicole commented on index.php
> +            </div>
Anotado

2022-03-02 16:38 UTC, hmiranda99 approved these changes
Gatissima!

2022-03-02 16:39 UTC, Ti-Alves approved these changes

2022-03-02 16:40 UTC, Palominha approved these changes

2022-03-02 16:41 UTC, gustavodesantana approved these changes

2022-03-02 16:42 UTC, MayaraPereira17 approved these changes
parabensss

2022-03-02 16:43 UTC, Gih08 approved these changes

2022-03-02 16:43 UTC, merged