Painel de usuarios
kvlsndkf/here pull request #27
Opened 2022-03-12 18:30 UTC by Palominha

Painel de Usuários

2022-03-12 18:33 UTC, garcia235 approved these changes

2022-03-12 18:36 UTC, Ti-Alves approved these changes

2022-03-12 20:57 UTC, MayaraPereira17 approved these changes

2022-03-13 13:45 UTC, emillienicole approved these changes
PERFEITO

2022-03-13 18:03 UTC, hmiranda99 requested changes
Só faltou ajustar o "Fale conosco".

E só uma ressalva que é lembrar de evitar estilizar diretamente as ´tags´ como por exemplo `h6`, `header`, `form` e afins. Criar classes para eles e estilizar e assim evitar conflitos. Mas, lembrando que isso não deve ser mudado aqui, é só um alerta para as próximas PR's.

2022-03-15 03:40 UTC, MayaraPereira17 requested changes

2022-03-15 03:40 UTC, MayaraPereira17 commented on views/pages/painel-usuarios/painel-usuario.css
> +    background-image:url(../../images/fundo-painel.svg);
só precisa de um ponto ficaria assim "url(./images/fundo-painel.svg)".

2022-03-15 11:02 UTC, hmiranda99 approved these changes
muito bom!

2022-03-15 11:03 UTC, hmiranda99 commented on views/pages/painel-usuarios/painel-usuario.css
> +    background-image:url(../../images/fundo-painel.svg);
mas o arquivo dela, tá dentro de uma pasta, que tá dentro de outra pasta. seria `./` se a imagem estivesse na mesma pasta que o arquivo.

2022-03-15 22:49 UTC, MayaraPereira17 commented on views/pages/painel-usuarios/painel-usuario.css
> +    background-image:url(../../images/fundo-painel.svg);
Entendi

2022-03-15 22:50 UTC, MayaraPereira17 approved these changes

2022-03-15 23:17 UTC, emillienicole approved these changes

2022-03-15 23:34 UTC, gustavodesantana approved these changes

2022-03-15 23:37 UTC, garcia235 approved these changes

2022-03-16 00:58 UTC, merged