Comunidade
kvlsndkf/here pull request #32
Opened 2022-03-14 12:13 UTC by garcia235

2022-03-14 14:05 UTC, hmiranda99 requested changes
### ➡️ **Observação 1**: O `container` da sessão não respeita o `container` utilizado na página;

![Captura de tela 2022-03-14 105551](https://user-images.githubusercontent.com/79329906/158186786-ac2ce8a9-95b3-4bcd-9e87-afff1489d1d6.png)

##

### ➡️ **Observação 2:** Atenção na hora de criar o nome da branch, ela está incorreta. Deve-se usar o pré-fixo `feat` ou `fix`;

##

### ➡️ **Observação 3:** Não foi adicionado o pessoal para reviwers, e nem as outras etapas de criador e a label. Atentar-se na próxima branch.

##

### ➡️ **Observação 4:** A sessão não está responsiva, além disso, está sobre a sessão acima;
![Captura de tela 2022-03-14 105940](https://user-images.githubusercontent.com/79329906/158187739-dd813f76-d988-45b0-a5b5-d0dcd89b1161.png)

##

🎉 Muito bom ter usado imagens em `.svg` deixou a qualidade bem mais bonita e parabéns por não estilizar diretamente as `tags`!

2022-03-16 03:22 UTC, Ti-Alves approved these changes

2022-03-16 03:23 UTC, Ti-Alves reviewed
Aprovado para dar continuidade porém favor realizar mudanças pedidas por outros integrantes

2022-03-19 00:10 UTC, emillienicole approved these changes
Perfeito, até me emociono desse jeito, assim que eu ver tudo junto eu choro ein

2022-03-19 13:03 UTC, Ti-Alves approved these changes

2022-03-19 17:27 UTC, hmiranda99 approved these changes

2022-03-19 18:52 UTC, gustavodesantana approved these changes

2022-03-19 19:47 UTC, MayaraPereira17 approved these changes

2022-03-19 20:30 UTC, Palominha approved these changes

2022-03-20 03:16 UTC, merged