Cadastro ETECs
kvlsndkf/here pull request #40
Opened 2022-03-19 13:09 UTC by Ti-Alves

Tela para visualização e manipulação das ETECs

2022-03-19 13:12 UTC, MayaraPereira17 approved these changes

2022-03-19 17:02 UTC, hmiranda99 requested changes
### Pontos encontrados:
**MENU**
> OK 🎉 ---- O link para a home do menu não foi colocado;
> OK 🎉 ---- O sublinhado continua na home, ele deveria estar em ETEC´s, ele serve para o usuário saber em que página está.

- O card para cadastro unitário, está o link para o cadastro em lote.

##

**TABELA**
> OK 🎉 ---- No input de pesquisa está faltando o ícone da lupa;
- O `Excluir` da tabela não está funcionando.


Parabéns pelo capricho, a responsividade está ok! 🎉 

##

**PR**
- Atenção com o nome da PR , ele está incorreto;
- `feat` para PRs de criação, `fix`para PRs de alteração.

2022-03-19 19:16 UTC, garcia235 approved these changes

2022-03-20 16:41 UTC, hmiranda99 approved these changes

2022-03-20 16:48 UTC, gustavodesantana approved these changes

2022-03-20 16:49 UTC, merged