List secretarias
kvlsndkf/here pull request #44
Opened 2022-03-19 23:17 UTC by MayaraPereira17

front-end pagina listas de secretarias

2022-03-19 23:24 UTC, hmiranda99 requested changes
**MENU**
> OK 🎉 -------- Link da opção `ETEC's` não está funcionando;
- A label para entrar na parte dos professores não tem 😢 

##

**TABELA**
> OK ------- Na barra de pesquisa, não tem o ícone da lupa.
- Tem o ícone na barra mas ele está torto, não está centralizado.
- O Scroll X tá bem desalinhado, segue imagem
![image](https://user-images.githubusercontent.com/79329906/159144413-decb4917-501b-49b1-b3f0-251fd82e7060.png)
- O botão excluir não está funcionando 😿 

##
**CARD**
> OK 🎉 ------ Você colocou um width fixo, deve colocar 100%, por causa do fixo ele não fica responsivo.

2022-03-20 02:30 UTC, hmiranda99 approved these changes

2022-03-20 02:57 UTC, Gih08 approved these changes

2022-03-20 02:57 UTC, emillienicole approved these changes

2022-03-20 02:59 UTC, gustavodesantana approved these changes

2022-03-20 03:15 UTC, merged