Feat/secretaria home
kvlsndkf/here pull request #45
Opened 2022-03-20 02:18 UTC by garcia235

new pull  request

2022-03-20 02:40 UTC, hmiranda99 reviewed
.

2022-03-20 02:40 UTC, hmiranda99 requested changes
**MENU**
- O droppdown não funciona, quando clica ele manda para a página das etec que é uma página que faz parte da instituição;

##

**CARD**
- A numeração não está alinhada com a logo;
- A logo está diferente da cor do card;

Como está:
![image](https://user-images.githubusercontent.com/79329906/159145618-28742a17-ee07-48bc-a3fe-670a9b0174de.png)

Como deve ser:
![image](https://user-images.githubusercontent.com/79329906/159145610-beb78f95-0af9-495d-b9c7-3de1ac29ff2e.png)

- O alinhamento dos cards na versão mobile não foi ajustado

![card](https://user-images.githubusercontent.com/79329906/159145663-81d41536-0c14-47e6-96ef-2fe426ec24aa.png)

2022-03-22 04:55 UTC, Ti-Alves approved these changes

2022-03-22 11:56 UTC, hmiranda99 approved these changes

2022-03-22 14:50 UTC, Palominha approved these changes

2022-03-22 14:55 UTC, kaique831 approved these changes

2022-03-22 14:57 UTC, merged