Feat/tela login
kvlsndkf/here pull request #5
Opened 2022-03-02 17:55 UTC by MayaraPereira17

1° Tela de login

2022-03-02 20:14 UTC, Gih08 approved these changes, later dismissed

2022-03-02 20:39 UTC, gustavodesantana approved these changes, later dismissed

2022-03-02 20:58 UTC, hmiranda99 requested changes

2022-03-02 20:58 UTC, hmiranda99 commented on Login.page.php
> +        </div>
Faltou o peso da fonte do "Fale conosco" `font-weigth=800`. Ela se encontra no arquivo global.

2022-03-03 16:26 UTC, garcia235 approved these changes, later dismissed

2022-03-04 22:40 UTC, emillienicole requested changes

2022-03-04 22:40 UTC, emillienicole commented on views/styles/style.login.page.css
> +}
é melhor deixar a formatação de página apenas com o css global, se não pode conflitar e bugar

2022-03-04 22:40 UTC, emillienicole commented on views/styles/style.login.page.css
> +    color: #240046;
a intenção é que usemos as variáveis em todos os valores correspondentes, porque todas as cores que você precisa que estão no protótipo estão armazenadas nelas

2022-03-04 23:41 UTC, emillienicole requested changes
colocar o favicon, pode pegar o arquivo do meu projeto que ele funciona bonitinho. está em views/images/favicon.png

vídeo para auxilio, está no **minuto 12:13**

https://www.youtube.com/watch?v=1ZeettFfxys&t=736s&ab_channel=CursoemVídeo

2022-03-04 23:41 UTC, emillienicole commented on views/styles/style.login.page.css
> +}
colocar:

**font-family: var(--font);**

para aplicar a fonte manrope, assim como o protótipo

2022-03-05 03:17 UTC, MayaraPereira17 commented
já foram resolvidos os devidos problemas, em breve subirei a pr

2022-03-08 01:16 UTC, hmiranda99 approved these changes

2022-03-08 22:50 UTC, emillienicole approved these changes

2022-03-08 22:53 UTC, garcia235 approved these changes

2022-03-09 01:23 UTC, Palominha approved these changes

2022-03-09 01:24 UTC, Palominha approved these changes

2022-03-09 10:31 UTC, merged