feat/list-course
kvlsndkf/here pull request #50
Opened 2022-03-21 00:49 UTC by Ti-Alves

2022-03-21 15:09 UTC, hmiranda99 approved these changes
**PÁGINA**
- Está faltando o scroll X da tabela;

Muito bom, parabéns pelo capricho!

- O nome da branch está incorreto, está faltando o pré-fixo

2022-03-21 15:10 UTC, hmiranda99 requested changes
**PÁGINA**
- Está faltando o scroll X da tabela;

Muito bom, parabéns pelo capricho!

- O nome da branch está incorreto, está faltando o pré-fixo

2022-03-21 15:14 UTC, MayaraPereira17 approved these changes

2022-03-21 22:44 UTC, hmiranda99 approved these changes

2022-03-21 23:10 UTC, emillienicole approved these changes
arrasou

2022-03-22 00:59 UTC, gustavodesantana approved these changes

2022-03-22 02:54 UTC, garcia235 approved these changes

2022-03-22 06:04 UTC, emillienicole approved these changes

2022-03-22 14:39 UTC, merged