Feat/recursos here
kvlsndkf/here pull request #7
Opened 2022-03-02 20:37 UTC by Palominha

Parte de Recursos

2022-03-05 02:25 UTC, emillienicole requested changes

2022-03-05 02:25 UTC, emillienicole commented on views/pages/landing-page-here/landing-page-here.page.php
> -        <script type="text/javascript" src="/views/js/index.scripts.js"></script>
meu script perto do fechamento do body

2022-03-05 02:25 UTC, emillienicole commented on views/pages/landing-page-here/landing-page-here.page.php
>          <div class="container">
mudar o nome da class para "container-card"

2022-03-05 02:25 UTC, emillienicole commented on views/pages/landing-page-here/landing-page-here.page.php
> +    </script>
ele poderia estar no script do vanilla ou não funcionaria?

2022-03-05 02:25 UTC, emillienicole commented on views/pages/landing-page-here/recursos.style.css
> +@import url('https://fonts.googleapis.com/css2?family=Manrope:wght@600&display=swap');
retirar import e transferir todas classes para o css já existente "hero.style.css", para usarmos um só style e aí pode apagar o arquivo (depois que der tudo certo)

2022-03-05 02:25 UTC, emillienicole commented on views/pages/landing-page-here/recursos.style.css
> +    background-color: #F9DAFB;
usar variaveis de cores, peso, tamanho de fonte e fonte

2022-03-05 02:25 UTC, emillienicole commented on views/pages/landing-page-here/recursos.style.css
> +.container{
mudar todos os .container para .container-card

2022-03-05 02:25 UTC, emillienicole commented on views/pages/landing-page-here/vanilla-tilt.js
> +var VanillaTilt = (function () {
mover esse js para a pasta "js"

2022-03-05 02:25 UTC, emillienicole commented on views/pages/landing-page-here/recursos.style.css
> +    background-image:url(../../images/manchas4.png);
responsividade do background

2022-03-05 02:25 UTC, emillienicole commented on views/pages/landing-page-here/recursos.style.css
> +}
adicionar font weight extrabold

2022-03-06 20:58 UTC, hmiranda99 approved these changes
Mandou bem!

2022-03-06 21:13 UTC, emillienicole approved these changes

2022-03-06 21:14 UTC, garcia235 approved these changes

2022-03-06 21:38 UTC, Ti-Alves approved these changes

2022-03-06 22:03 UTC, merged